version: '3.1'
services:  
    mariadb:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            # MYSQL_DATABASE: test_db
            # MYSQL_USER: root
            # MYSQL_PASSWORD: asdf
        volumes:
            - ./mariadb:/var/lib/mysql
        ports:
            - "3306:3306"

